# Generated by Django 4.2.5 on 2023-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="blup", max_length=100),
            preserve_default=False,
        ),
    ]
