# Generated by Django 4.2.5 on 2023-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk_app", "0002_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
