# Generated by Django 4.2.5 on 2023-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk_app", "0004_contributor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("Contributeur", "Contributor"), ("Auteur", "Author")],
                max_length=50,
            ),
        ),
    ]
